CREATE DATABASE NEW_RECORDS;
USE NEW_RECORDS;

CREATE TABLE EMPLOYEES(
EMPL_ID INT PRIMARY KEY,
EMPL_NAME VARCHAR(30),
EMPL_PALCE VARCHAR(50),
EMPL_DESIGNATION VARCHAR(25),
EMPL_MODES VARCHAR(30),
EMPL_SALARY INT NOT NULL);

CREATE TABLE PAYROLL(
PAYROLL_ID INT PRIMARY KEY,
EMPL_ID INT,
PAYROLL_BANK VARCHAR(40),
PAYROLL_DATE DATE,
FOREIGN KEY(EMPL_ID) REFERENCES EMPLOYEES(EMPL_ID)); 

INSERT INTO EMPLOYEES(EMPL_ID, EMPL_NAME,EMPL_PALCE,EMPL_DESIGNATION, EMPL_MODES,EMPL_SALARY) VALUES
(101, "HARRY BROOK", "LONDON", " FRONTEND DEVELOPER", "CREDIT", 48000),
(102, "TEMBA BAVUMA", "NORTH KORIA", "BACKEND DEVELOPER", "DEBIT", 58000),
(103, "JOE ROOT", "LONDON", "DATA ENGINEER", "LOAN", 68000),
(104, "DWANE BRAVO", "WEST INDIES", "SOFTWARE ENGINEER", "SAVINGS", 78000),
(105, "ANDRE RUSSEL", "NORTH AFRICA", "ML ENGINEER", "DEBIT",38000),
(106, "SHIMRON HWTMAYER", "AUSTRALIA", "DATA SCIENTIST", "CREDIT", 88000),
(107, "KEEMAR ROCH", "SOUTH AFRICA", "DATA ANALYST", "DEBIT", 95000),
(108, "GRAME SMITH", "AMERICA", "DATA ENGINEER", "LOAN", 100000),
(109, "MARCO JANSEN", "NORTH ANERICA", "AI ENGINEER", "SAVINGS", 88000),
(110, "DAVID MILLER", "SOUTH AMERICA", "ML ENGINEER", "CREDIT", 120000),
(111, "PAT CUMMINS", "AUSTRALIA", "DATA SCIENTIST", "CURRENT", 150000),
(112, "HENRIC KLASSEN", "SOUTH AFRICA", "DATA ANALYST", "LOAN", 135000),
(113, "DEJAWUU", "AMERICA", "SOFTWARE ENGINEER", "CURRENT", 30000);

SELECT * FROM EMPLOYEES;

SELECT EMPL_NAME FROM EMPLOYEES;

SELECT EMPL_NAME , EMPL_SALARY FROM EMPLOYEES;

SELECT * FROM EMPLOYEES 
WHERE EMPL_PALCE = "LONDON" OR
EMPL_PALCE = "AMERICA";

SELECT * FROM EMPLOYEES
WHERE EMPL_SALARY > 60000;

SELECT * FROM EMPLOYEES 
WHERE EMPL_MODES = "SAVINGS" OR
EMPL_MODES = "LOAN";

SELECT * FROM EMPLOYEES WHERE 
EMPL_DESIGNATION = "DATA ENGINEER" OR 
EMPL_DESIGNATION = "DATA SCIENTIST";

SELECT DISTINCT(EMPL_PALCE) AS UNIQUE_PLACE, EMPL_NAME FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE
EMPL_NAME LIKE "%N"OR
EMPL_NAME LIKE "A%" OR 
EMPL_NAME LIKE "%T";

SELECT * FROM EMPLOYEES WHERE
EMPL_SALARY >= 40000 AND EMPL_SALARY < 80000;

SELECT * FROM EMPLOYEES WHERE EMPL_SALARY != 60000;

SELECT * FROM EMPLOYEES WHERE EMPL_SALARY IS NOT NULL;

SELECT EMPL_NAME,EMPL_MODES FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE EMPL_DESIGNATION
!= "DATA ENGINEEER" OR "DATA SCIENTIST";

SELECT * FROM EMPLOYEES ORDER BY EMPL_SALARY DESC;

SELECT * FROM EMPLOYEES ORDER BY EMPL_SALARY ASC;

SELECT * FROM EMPLOYEES ORDER BY EMPL_SALARY DESC LIMIT 5;

SELECT EMPL_SALARY AS INCOME FROM EMPLOYEES;

SELECT DISTINCT(EMPL_DESIGNATION) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE EMPL_PALCE != "AUSTRALIA";

SELECT * FROM EMPLOYEES WHERE EMPL_PALCE != "LONDON";

SELECT LENGTH(EMPL_NAME) AS LENGTH_OF_THE_NAME FROM
EMPLOYEES;

SELECT CONCAT(EMPL_NAME, EMPL_SALARY) AS INFORMATION FROM EMPLOYEES;

SELECT EMPL_NAME, (EMPL_SALARY * 2) AS MULTIPLY_BY_2 FROM EMPLOYEES;



UPDATE EMPLOYEES
SET EMPL_SALARY = ROUND(EMPL_SALARY, -3);

SELECT * FROM EMPLOYEES WHERE 
EMPL_SALARY BETWEEN 50000 AND 98000;

SELECT * FROM EMPLOYEES WHERE 
EMPL_PALCE IN ("SOUTH AFRICA") OR
EMPL_PALCE IN ("AMERICA"); 

SELECT * FROM EMPLOYEES WHERE
EMPL_NAME LIKE "A%";

SELECT EMPL_NAME, LOWER(EMPL_NAME) FROM EMPLOYEES;


SELECT EMPL_NAME ,RIGHT(EMPL_NAME, 3) AS FIRST_THREE_CHAR  FROM EMPLOYEES;

SELECT EMPL_NAME FROM EMPLOYEES WHERE 
EMPL_NAME NOT LIKE "A%";

SELECT * FROM EMPLOYEES WHERE 
EMPL_NAME LIKE "%A%";

SELECT * FROM EMPLOYEES 
WHERE EMPL_NAME LIKE "%S__";

SELECT * FROM EMPLOYEES
WHERE EMPL_SALARY = 88000 OR EMPL_PALCE = "NORTH ANERICA";

SELECT * FROM EMPLOYEES ORDER BY EMPL_SALARY DESC
LIMIT 3;

SELECT * FROM EMPLOYEES 
ORDER BY EMPL_SALARY ASC 
LIMIT 1 OFFSET 2;

SELECT * FROM EMPLOYEES
ORDER BY EMPL_SALARY ASC ;

SELECT *  FROM EMPLOYEES
WHERE EMPL_SALARY < (SELECT MAX(EMPL_SALARY) FROM EMPLOYEES);

SELECT EMPL_ID, EMPL_NAME, EMPL_MODES, EMPL_SALARY, 
DENSE_RANK() OVER (ORDER BY EMPL_SALARY ASC) AS SECOND_LOWEST_SALARY
FROM EMPLOYEES
LIMIT 1 OFFSET 1;

SELECT DISTINCT(EMPL_SALARY) AS THIRD_HIGHEST_SALARY
FROM EMPLOYEES
ORDER BY EMPL_SALARY DESC
LIMIT 1 OFFSET 2;

SELECT EMPL_NAME, LENGTH(EMPL_NAME) 
AS TOTAL_LENGHT FROM EMPLOYEES
GROUP BY EMPL_NAME;

SELECT * FROM EMPLOYEES WHERE
EMPL_ID % 2 = 0;

SELECT * FROM  EMPLOYEES 
WHERE EMPL_NAME NOT LIKE "%Z%";

SELECT * FROM EMPLOYEES
WHERE EMPL_PALCE IS NOT NULL;




SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE 
EMPL_SALARY = 135000 OR EMPL_PALCE = "NORTH AFRICA";

SELECT * FROM EMPLOYEES
WHERE EMPL_SALARY > 80000;


SET EMPLOYEES
UPDATE EMPL_SALARY = ROUND(EMPL_SALARY, -3);
